/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as partyBetSol from "./partyBet.sol";
export type { partyBetSol };
export type { Lock } from "./Lock";
export * as factories from "./factories";
export { Lock__factory } from "./factories/Lock__factory";
export type { PartyBet } from "./partyBet.sol/PartyBet";
export { PartyBet__factory } from "./factories/partyBet.sol/PartyBet__factory";
